# This is a basic workflow that is manually triggered

name: 1a Hola Mundo

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo!"
